env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  LocalFile {
    path = "/home/seed/rides-analytics/input/trips.csv"
    file_format_type = "csv"
    skip_header_row_number = 1
    table_name = "trips"

    schema = {
      fields {
        trip_id = string
        driver_id = string
        city = string
        pickup_ts = string
        dropoff_ts = string
        distance_km = double
        fare = double
      }
    }
  }
}

transform {
  Sql {
    query = """
      SELECT
        trip_id,
        driver_id,
        city,
        pickup_ts,
        dropoff_ts,
        distance_km,
        fare
      FROM trips
      WHERE distance_km IS NOT NULL
        AND distance_km > 0
        AND fare IS NOT NULL
        AND dropoff_ts > pickup_ts
    """
  }
}

sink {
  HdfsFile {
    path = "/user/student/rides_pipeline/clean_trips"
    file_format_type = "csv"
    write_mode = "overwrite"

    "fs.defaultFS" = "hdfs://localhost:9000"

    hdfs_site_path = "/home/seed/hadoop-3.3.6/etc/hadoop/hdfs-site.xml"
    core_site_path = "/home/seed/hadoop-3.3.6/etc/hadoop/core-site.xml"
  }
}
