env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  HdfsFile {
    path = "/user/student/rides_pipeline/avg_fare_per_km"
    file_format_type = "text"
    field_delimiter = "\t"

    fs.defaultFS = "hdfs://localhost:9000"

    schema = {
      fields {
        city = string
        fare_per_km = double
      }
    }
  }
}

transform {
  Sql {
    query = """
      SELECT city, fare_per_km
      FROM default
      WHERE fare_per_km > 17
    """
  }
}

sink {
  LocalFile {
    path = "/home/seed/rides-analytics/output"
    file_format_type = "csv"

    custom_filename = true
    file_name_expression = "${transactionId}_costly"
  }
}
