env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  HdfsFile {
    path = "/user/student/rides_pipeline/avg_speed"
    file_format_type = "text"
    field_delimiter = "\t"

    fs.defaultFS = "hdfs://localhost:9000"

    schema = {
      fields {
        city = string
        average_speed = double
      }
    }
  }
}

transform {
  Sql {
    query = """
      SELECT city, average_speed
      FROM default
      WHERE average_speed <= 45
    """
  }
}

sink {
  LocalFile {
    path = "/home/seed/rides-analytics/output"
    file_format_type = "csv"

    custom_filename = true
    file_name_expression = "${transactionId}_hightraffic"
  }
}
