env {
	parallelism = 1
	job.mode = "BATCH"
}
source {
	LocalFile {
		path = "/home/seed/seatunnel-verification/students.csv"
		file_format_type = "csv"
		skip_header_row_number = 1
		schema = {
			fields {
				student_id = int
				student_name = string
				age = int
				score = int
				department = string
				}
			}
		}
	}
transform {
	FieldMapper {
		field_mapper = {
			student_id = student_id
			student_name = name
			score = marks
			department = department
			}
		}
	}
sink {
	Console {}
}
